### ISSUE TITLE
Is filename and content-disposition part of the datauri standard?

### ISSUE THREAD

**Issue by mofosyne** [ooxi/jdatauri#2]
I know charset is known by most browser parser (and [wikipedia](https://en.wikipedia.org/wiki/Data_URI_scheme) ). It seems like datauri is a dead standard, where most people are only keeping to rfc3986.

But I never seen "filename" and "content-disposition" in use in the wild however.

I'm trying to extend datauri in a manner that is in keeping with how datauri would be extended if used in a QR code context (aka split across multiple QR codes), for a pet project [TagDrop](https://github.com/mofosyne/tagdrop) . So if there is a existing extended standard that I should be aware of to avoid conflict with, I would like to do so. (e.g. recommended key name for sequence number, crc, compression type, or md5 hash etc...)

**Comment by ooxi** [comment]
[RFC2397 section three](https://tools.ietf.org/html/rfc2397#section-3) allows an arbitrary number of parameters. I'm not aware of an extended standard defining additional parameter names. So if you want to use data URI parameters I'd suggest prefixing them with `x-`.

Nevertheless I would not recommend using vendor specific data URI parameters since I would bet not many implementations would support parsing those. Instead I would recommend switching from GIF to PNG and use a custom PNG chunk to embed your information.

I'm going to close this issue but feel free to continue the discussion.
